import 'package:flutter_challenges/utils/assets.dart';

class NewsModel {
  final String id;
  final String title;
  final String autherName;
  final String autherImg;
  final String channel;
  final String category;
  final String imgUrl;
  final String date;
  final String channelImg;
  final List<String> content;

  NewsModel({
    required this.id,
    required this.title,
    required this.channel,
    required this.autherName,
    required this.autherImg,
    this.category = 'Other',
    required this.imgUrl,
    required this.date,
    required this.channelImg,
    required this.content,
  }); // change it later
}

List<NewsModel> dummyBreakingNews = [
  NewsModel(
    id: '1',
    title: 'Alexandria wears modified helmet races',
    channel: 'CNN Indonesia',
    autherName: 'McKindney',
    autherImg: AppAssets.carouselHomePageAssets1,
    channelImg: AppAssets.cnnImg,
    imgUrl: AppAssets.carouselHomePageAssets1,
    date: '6 hours ago',
    content: [
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
    ],
  ),
  NewsModel(
    id: '2',
    title: 'Alexandria wears modified helmet races',
    channel: 'BBC',
    autherName: 'Rosemary',
    autherImg: AppAssets.carouselHomePageAssets1,
    channelImg: AppAssets.bbcImg,
    imgUrl: AppAssets.carouselHomePageAssets1,
    date: '6 hours ago',
    content: [
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
    ],
  ),
  NewsModel(
    id: '3',
    title: 'Alexandria wears modified helmet races',
    channel: 'National',
    autherName: 'McKindney',
    channelImg: AppAssets.cnnImg,
    autherImg: AppAssets.carouselHomePageAssets1,
    imgUrl: AppAssets.carouselHomePageAssets1,
    date: '6 hours ago',
    content: [
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
    ],
  ),
  NewsModel(
    id: '4',
    title: 'Alexandria wears modified helmet races',
    channel: 'CNN',
    autherName: 'Rosemary',
    channelImg: AppAssets.cnnImg,
    autherImg: AppAssets.carouselHomePageAssets1,
    imgUrl: AppAssets.carouselHomePageAssets1,
    date: '6 hours ago',
    content: [
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
    ],
  ),
];

List<NewsModel> dummyRecommendationNews = [
  NewsModel(
    id: '5',
    title: 'What Training Do Vollyball Players Need?',
    autherName: 'McKindney',
    category: 'Sports',
    autherImg: AppAssets.carouselHomePageAssets1,
    imgUrl: AppAssets.tempBreakingNewImage1,
    channel: 'CNN',
    channelImg: AppAssets.cnnImg,
    date: 'Feb27,2023',
    content: [
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
    ],
  ),
  NewsModel(
    id: '6',
    title: 'Secondary school places: When do parents find out?',
    category: 'Education',
    autherName: 'Rosemary',
    channelImg: AppAssets.bbcImg,
    autherImg: AppAssets.carouselHomePageAssets1,
    imgUrl: AppAssets.tempBreakingNewImage3,
    channel: 'BBC',
    date: 'Feb28,2023',
    content: [
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
    ],
  ),
  NewsModel(
    id: '7',
    title: 'What Training Do Vollyball Players Need?',
    autherName: 'McKindney',
    category: 'Sports',
    channelImg: AppAssets.cnnImg,
    autherImg: AppAssets.carouselHomePageAssets1,
    imgUrl: AppAssets.tempBreakingNewImage1,
    channel: 'Notional',
    date: 'Feb27,2023',
    content: [
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
    ],
  ),
  NewsModel(
    id: '8',
    title: 'Secondary school places: When do parents find out?',
    category: 'Education',
    autherName: 'Rosemary',
    channel: 'CNN',
    channelImg: AppAssets.cnnImg,
    autherImg: AppAssets.carouselHomePageAssets1,
    imgUrl: AppAssets.tempBreakingNewImage3,
    date: 'Feb28,2023',
    content: [
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
      AppAssets.dummyContent,
    ],
  ),
];
